teams:
    resource: ../../src/Teams/Controller/
    type: annotation

players:
    resource: ../../src/Players/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
