doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Player:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Players/Entity'
                prefix: 'App\Players\Entity'
                alias: Players
            Team:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Teams/Entity'
                prefix: 'App\Teams\Entity'
                alias: Teams
